"""empty message

Revision ID: 056cd7c3dffb
Revises: 52ba3eb00bd8
Create Date: 2023-03-13 11:17:42.100777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056cd7c3dffb'
down_revision = '52ba3eb00bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('route_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('route_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
