"""empty message

Revision ID: 0c16bcf08c94
Revises: 07f508644835
Create Date: 2023-02-10 18:36:07.428368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c16bcf08c94'
down_revision = '07f508644835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint('route_end_location_text_key', type_='unique')
        batch_op.drop_constraint('route_start_location_text_key', type_='unique')
        batch_op.drop_column('start_location_text')
        batch_op.drop_column('end_location_text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_location_text', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_location_text', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('route_start_location_text_key', ['start_location_text'])
        batch_op.create_unique_constraint('route_end_location_text_key', ['end_location_text'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
