"""empty message

Revision ID: 15697a902037
Revises: 62cf54343daa
Create Date: 2023-02-15 18:45:40.667247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15697a902037'
down_revision = '62cf54343daa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint('route_end_location_text_key', type_='unique')
        batch_op.drop_constraint('route_interest_text_key', type_='unique')
        batch_op.drop_constraint('route_start_location_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.create_unique_constraint('route_start_location_text_key', ['start_location_text'])
        batch_op.create_unique_constraint('route_interest_text_key', ['interest_text'])
        batch_op.create_unique_constraint('route_end_location_text_key', ['end_location_text'])

    # ### end Alembic commands ###
