"""empty message

Revision ID: 181f999b0400
Revises: 51358cd22d66
Create Date: 2023-02-03 20:21:36.771161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181f999b0400'
down_revision = '51358cd22d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bike',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('bike_photo', sa.String(length=250), nullable=False),
    sa.Column('ask_1_license', sa.String(length=250), nullable=False),
    sa.Column('ask_11_limitable', sa.Boolean(), nullable=True),
    sa.Column('ask_2_wheels', sa.String(length=250), nullable=False),
    sa.Column('ask_3_surface', sa.String(length=250), nullable=False),
    sa.Column('ask_31_surface_offroad', sa.String(length=250), nullable=False),
    sa.Column('ask_311_motor_offroad', sa.String(length=250), nullable=False),
    sa.Column('ask_32_custom', sa.String(length=250), nullable=False),
    sa.Column('ask_321_refrigeration', sa.String(length=250), nullable=False),
    sa.Column('ask_4_comodity', sa.String(length=250), nullable=False),
    sa.Column('ask_5_style', sa.String(length=250), nullable=False),
    sa.Column('ask_6_price', sa.String(length=250), nullable=False),
    sa.Column('ask_7_new', sa.String(length=250), nullable=False),
    sa.Column('ask_8_response', sa.String(length=250), nullable=False),
    sa.Column('ask_9_reliability', sa.String(length=250), nullable=False),
    sa.Column('ask_10_power', sa.String(length=250), nullable=False),
    sa.Column('ask_11_armor', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bike_photo'),
    sa.UniqueConstraint('name')
    )
    op.add_column('favorite', sa.Column('bike_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'bike', ['bike_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'bike_id')
    op.drop_table('bike')
    # ### end Alembic commands ###
