"""empty message

Revision ID: 1f95e03b71c8
Revises: 280777f5c30f
Create Date: 2023-02-06 13:51:17.101635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f95e03b71c8'
down_revision = '280777f5c30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'answer_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('answer', 'answer_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('question', 'question_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('question', 'question_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('answer', 'answer_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
