"""empty message

Revision ID: 280777f5c30f
Revises: fbc18559ac3b
Create Date: 2023-02-06 13:26:56.680321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280777f5c30f'
down_revision = 'fbc18559ac3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike', 'brand',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('bike', 'model',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bike', 'model',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('bike', 'brand',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
