"""empty message

Revision ID: 51358cd22d66
Revises: 86bff2cad45c
Create Date: 2023-02-03 20:18:20.609408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51358cd22d66'
down_revision = '86bff2cad45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('fav_type', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite', 'fav_type')
    # ### end Alembic commands ###
