"""empty message

Revision ID: 53eeef9377c0
Revises: 1f95e03b71c8
Create Date: 2023-02-06 14:13:36.953134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eeef9377c0'
down_revision = '1f95e03b71c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('answer', sa.String(length=250), nullable=True))
    op.drop_column('answer', 'answer_1_license')
    op.drop_column('answer', 'answer_31_surface_offroad')
    op.drop_column('answer', 'answer_3_surface')
    op.drop_column('answer', 'answer_2_wheels')
    op.drop_column('answer', 'answer_6_price')
    op.drop_column('answer', 'answer_311_motor_offroad')
    op.drop_column('answer', 'answer_32_custom')
    op.drop_column('answer', 'answer_7_new')
    op.drop_column('answer', 'answer_321_refrigeration')
    op.drop_column('answer', 'answer_11_limitable')
    op.drop_column('answer', 'answer_10_power')
    op.drop_column('answer', 'answer_8_response')
    op.drop_column('answer', 'answer_4_comodity')
    op.drop_column('answer', 'answer_9_reliability')
    op.drop_column('answer', 'answer_5_style')
    op.drop_column('answer', 'answer_11_armor')
    op.add_column('question', sa.Column('question', sa.String(length=250), nullable=True))
    op.add_column('question', sa.Column('text_question', sa.String(length=250), nullable=True))
    op.drop_column('question', 'question_7_new')
    op.drop_column('question', 'question_8_response')
    op.drop_column('question', 'question_32_custom')
    op.drop_column('question', 'question_11_limitable')
    op.drop_column('question', 'question_4_comodity')
    op.drop_column('question', 'question_1_license')
    op.drop_column('question', 'question_3_surface')
    op.drop_column('question', 'question_321_refrigeration')
    op.drop_column('question', 'question_6_price')
    op.drop_column('question', 'question_311_motor_offroad')
    op.drop_column('question', 'question_11_armor')
    op.drop_column('question', 'question_9_reliability')
    op.drop_column('question', 'question_10_power')
    op.drop_column('question', 'question_2_wheels')
    op.drop_column('question', 'question_31_surface_offroad')
    op.drop_column('question', 'question_5_style')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question_5_style', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_31_surface_offroad', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_2_wheels', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_10_power', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_9_reliability', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_11_armor', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_311_motor_offroad', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_6_price', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_321_refrigeration', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_3_surface', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_1_license', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_4_comodity', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_11_limitable', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_32_custom', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_8_response', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('question', sa.Column('question_7_new', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('question', 'text_question')
    op.drop_column('question', 'question')
    op.add_column('answer', sa.Column('answer_11_armor', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_5_style', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_9_reliability', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_4_comodity', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_8_response', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_10_power', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_11_limitable', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_321_refrigeration', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_7_new', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_32_custom', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_311_motor_offroad', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_6_price', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_2_wheels', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_3_surface', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_31_surface_offroad', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('answer', sa.Column('answer_1_license', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('answer', 'answer')
    # ### end Alembic commands ###
