"""empty message

Revision ID: 58e3f12e966f
Revises: b89bc7045d4e
Create Date: 2023-02-08 19:20:56.168640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e3f12e966f'
down_revision = 'b89bc7045d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographer', schema=None) as batch_op:
        batch_op.alter_column('location_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('instagram',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('services_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('find_me_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.drop_constraint('photographer_find_me_text_key', type_='unique')
        batch_op.drop_constraint('photographer_location_text_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photographer', schema=None) as batch_op:
        batch_op.create_unique_constraint('photographer_location_text_key', ['location_text'])
        batch_op.create_unique_constraint('photographer_find_me_text_key', ['find_me_text'])
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('location_name',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('find_me_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('services_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('instagram',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('location_text',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
