"""empty message

Revision ID: 62cf54343daa
Revises: ebb98f0ccb5e
Create Date: 2023-02-13 10:19:38.518029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cf54343daa'
down_revision = 'ebb98f0ccb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_question_id', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'question', ['previous_question_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('previous_question_id')

    # ### end Alembic commands ###
