"""empty message

Revision ID: 811e8e898f41
Revises: d0b398553447
Create Date: 2023-02-06 19:14:33.040396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811e8e898f41'
down_revision = 'd0b398553447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('current_question_id', sa.String(length=250), nullable=True))
    op.drop_constraint('answer_question_id_fkey', 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'question', ['current_question_id'], ['id'])
    op.drop_column('answer', 'question_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('question_id', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key('answer_question_id_fkey', 'answer', 'question', ['question_id'], ['id'])
    op.drop_column('answer', 'current_question_id')
    # ### end Alembic commands ###
