"""empty message

Revision ID: 86bff2cad45c
Revises: 22833abb368a
Create Date: 2023-02-03 19:57:50.134002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bff2cad45c'
down_revision = '22833abb368a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photographer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=250), nullable=False),
    sa.Column('passsword', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('location_text', sa.String(length=250), nullable=False),
    sa.Column('instagram', sa.String(length=250), nullable=False),
    sa.Column('services_text', sa.String(length=250), nullable=False),
    sa.Column('find_me_text', sa.String(length=250), nullable=False),
    sa.Column('location_name', sa.String(length=250), nullable=False),
    sa.Column('latitude', sa.String(length=250), nullable=False),
    sa.Column('longitude', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('find_me_text'),
    sa.UniqueConstraint('instagram'),
    sa.UniqueConstraint('location_text'),
    sa.UniqueConstraint('services_text'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_location_text', sa.String(length=250), nullable=False),
    sa.Column('end_location_text', sa.String(length=250), nullable=False),
    sa.Column('interest_text', sa.String(length=250), nullable=False),
    sa.Column('start_location_name', sa.String(length=250), nullable=False),
    sa.Column('start_latitude', sa.String(length=250), nullable=False),
    sa.Column('start_longitude', sa.String(length=250), nullable=False),
    sa.Column('end_location_name', sa.String(length=250), nullable=False),
    sa.Column('end_latitude', sa.String(length=250), nullable=False),
    sa.Column('end_longitude', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end_location_text'),
    sa.UniqueConstraint('interest_text'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('start_location_text')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographer.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('path', sa.String(length=250), nullable=False),
    sa.Column('photo_type', sa.String(length=250), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('photographer_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photographer_id'], ['photographer.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('photo_type')
    )
    op.add_column('user', sa.Column('user_name', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('passsword', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'active')
    op.drop_column('user', 'passsword')
    op.drop_column('user', 'user_name')
    op.drop_table('photo')
    op.drop_table('favorite')
    op.drop_table('route')
    op.drop_table('photographer')
    # ### end Alembic commands ###
