"""empty message

Revision ID: a4dd85d84e76
Revises: 15697a902037
Create Date: 2023-02-16 11:24:04.369132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4dd85d84e76'
down_revision = '15697a902037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.alter_column('ask_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('ask_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bike', schema=None) as batch_op:
        batch_op.alter_column('ask_11_armor',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_10_power',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_9_reliability',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_8_response',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_7_new',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_6_price',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_5_style',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_4_comodity',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_321_refrigeration',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_32_custom',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_311_motor_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_31_surface_offroad',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_3_surface',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_2_wheels',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_11_limitable',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('ask_1_license',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###
