"""empty message

Revision ID: b89bc7045d4e
Revises: 87008d833394
Create Date: 2023-02-08 11:33:51.593537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b89bc7045d4e'
down_revision = '87008d833394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer', ['id'])
    op.create_unique_constraint(None, 'question', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    # ### end Alembic commands ###
