"""empty message

Revision ID: d0b398553447
Revises: 8d5e7a3a6443
Create Date: 2023-02-06 19:10:44.352462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0b398553447'
down_revision = '8d5e7a3a6443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer', ['id'])
    op.create_unique_constraint(None, 'question', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='unique')
    op.drop_constraint(None, 'answer', type_='unique')
    # ### end Alembic commands ###
