"""empty message

Revision ID: e0a26af2ff50
Revises: 58e3f12e966f
Create Date: 2023-02-10 13:48:29.764983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a26af2ff50'
down_revision = '58e3f12e966f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bike_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('photo_photo_type_key', type_='unique')
        batch_op.create_foreign_key(None, 'bike', ['bike_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('photo_photo_type_key', ['photo_type'])
        batch_op.drop_column('bike_id')

    # ### end Alembic commands ###
