"""empty message

Revision ID: f3ce7398d197
Revises: d4c4f9b9e2fd
Create Date: 2023-02-03 20:35:49.265296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ce7398d197'
down_revision = 'd4c4f9b9e2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('favorite', 'fav_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('fav_type', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.alter_column('favorite', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
